### ISSUE TITLE
log如下，求解

### ISSUE THREAD

**Issue by Huhu-Adora** [thundernet8/YouzanPayPortal#2]
YouzanPayPortal/node_modules/koa-bodyparser/index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/pay/dist/app.js:42:18)
error: Forever detected script exited with code: 1

**Comment by thundernet8** [comment]
要求Node 版本>8
