### ISSUE TITLE
求助，log如下：

### ISSUE THREAD

**Issue by hyxtj001** [thundernet8/YouzanPayPortal#5]
log或node运行，显示如下：
node dist/app.js
module.js:689
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/yuxinhuang/WebstormProjects/work/Youzan1/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
        /Users/yuxinhuang/WebstormProjects/work/Youzan1/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 89963
        /Users/yuxinhuang/WebstormProjects/work/Youzan1/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1789952 which is past end of file 89963
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yuxinhuang/WebstormProjects/work/Youzan1/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)

是否是sqlite模块安装问题？
> sqlite3@4.0.4 install /Users/yuxinhuang/WebstormProjects/work/Youzan1/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

执行npm audit fix --force
仍未解决。

求助，不胜感激！

**Comment by hyxtj001** [comment]
上述问题已解决，谢谢！
